#!/bin/bash
#SBATCH --job-name=baseline
#SBATCH --output=baseline.out
#SBATCH --error=baseline.err
#SBATCH --partition=ncpu
#SBATCH --nodes=1
#SBATCH --cpus-per-task=40
#SBATCH --mem-per-cpu=4G   # memory per cpu-core
#SBATCH --mail-type=fail         # send email if job fails
#SBATCH --mail-user=florian.oswald@gmail.com

# julia --project=. -e "using LandUse, Flux; LandUse.runestim()"

julia --project=. run.jl estimate --nwork=40 --maxsteps=105 --savefreq=210
