#!/bin/bash
#SBATCH --job-name=lambda1
#SBATCH --output=lambda1.out
#SBATCH --error=lambda1.err
#SBATCH --partition=ncpu
#SBATCH --nodes=1
#SBATCH --cpus-per-task=40
#SBATCH --mem-per-cpu=4G   # memory per cpu-core
#SBATCH --mail-type=fail         # send email if job fails
#SBATCH --mail-user=florian.oswald@gmail.com


julia --project=. run.jl estimate --nwork=40 --maxsteps=120 --savefreq=210 --scenario=agglola1
    